### ISSUE TITLE
Problems with the input

### ISSUE THREAD

**Issue by camillaadan** [sami-chaaban/PlotAkta#3]
"I'm experiencing an error message that says 'ERROR: No 'UV 1_280' (UV trace) column in the CSV file' when I try to read a tab-delimited UTF-16 file. However, I am certain that the file contains this column. Could you please provide me with an example input file so that I can test my code and figure out what might be causing this error?"

**Comment by sami-chaaban** [comment]
There was a problem with an expectation of a UV-260 column that I've just fixed. Does that solve your problem? I've attached a file that works. If you still have issues, attach your file so I can investigate.
[AktaFile.csv](https://github.com/sami-chaaban/PlotAkta/files/10908709/AktaFile.csv)
