### ISSUE TITLE
Modify Output

### ISSUE THREAD

**Issue by ulrich-eckhard** [sami-chaaban/PlotAkta#4]
Hey Sami!
really nice tool you have here - super nice. As I am a bit of a noob with such scripts, how would I "fix" the y-axis e.g.? I managed to change some colors, line thickness, labels, etc, but would like to e.g. fix the left y-axis from "-25" to "500" for UV280 (and 260) and the right y-axis (conductivity) e.g. from "0" to "25". How would I do that? Or maybe as a default, it would be good to have UV280 and UV260 with the same y-axis range. Hope you can help!
u

**Comment by ulrich-eckhard** [comment]
think managed to figure out now most things.

still fail though when truncating the x-axis (e.g. to 5-25ml) that the fractions aren't running "over" then (so they are not limited to the plot area but keep going). but maybe something easiest to edit in the csv file itself.

really nice script! :-)

**Comment by carterlablmb** [comment]
Glad its helpful. Did you try adding `plt.xlim(5,25)`?

**Comment by sami-chaaban** [comment]
Glad its helpful. Did you try adding `plt.xlim(5,25)`?

**Comment by ulrich-eckhard** [comment]
yes, and that worked nicely - but the "fractions" run "over" - enclosed a screenshot. not sure how to describe it.

![AktaFile](https://github.com/sami-chaaban/PlotAkta/assets/13509447/2ef05b94-7c72-4340-9fa0-6b808cd68d9d)

**Comment by sami-chaaban** [comment]
Add `clip_on=True` to the end of the relevant `ax.text(...)` line. The one to change depends on the options you chose, you could just add it to all of them.

**Comment by ulrich-eckhard** [comment]
worked like a charm! amazing! big big thanks again!
